# Autogenerated wrapper script for ocl_icd_jll for aarch64-apple-darwin
export cllayerinfo, libocl_icd

JLLWrappers.@generate_wrapper_header("ocl_icd")
JLLWrappers.@declare_library_product(libocl_icd, "@rpath/libOpenCL.1.dylib")
JLLWrappers.@declare_executable_product(cllayerinfo)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libocl_icd,
        "lib/libOpenCL.1.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cllayerinfo,
        "bin/cllayerinfo",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
